#!/usr/bin/env sh

set -e

java \
    -Xmx1g \
    -XX:MaxMetaspaceSize=1g \
    -XX:MetaspaceSize=250m \
    -Duser.home=/opt/youtrack \
    -Ddatabase.location=/opt/youtrack/data \
    -Ddatabase.backup.location=/opt/youtrack/backup \
    -Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts \
    -Djavax.net.ssl.trustStorePassword=changeit \
    -Djetbrains.youtrack.disableBrowser=true \
    -Djetbrains.youtrack.enableGuest=false \
    -Djava.awt.headless=true \
    -Djetbrains.youtrack.disableCheckForUpdate=true \
    -Djava.security.egd=/dev/urandom \
    -jar /opt/youtrack/bin/youtrack.jar 80